---
- name: add rpm key
  rpm_key: state=present key=https://monitoring.api.rackspacecloud.com/pki/agent/redhat-6.asc

- name: setup repo file
  template: src=RedHat.repo.j2 dest=/etc/yum.repos.d/rackspace-cloud-monitoring.repo owner=root group=root mode=0644

- name: install the agent
  yum: name=rackspace-monitoring-agent state=present
